# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Kontakt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kontakt
  pod 'SwiftGen'
  pod 'PhoneNumberKit', '~> 2.1'

  target 'KontaktTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KontaktUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
